name: Publish Production

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Which package to publish'
        required: true
        type: choice
        options:
          - 'packages/identity-models'
          - 'packages/identity-connector-entity-storage'
          - 'packages/identity-connector-iota'
          - 'packages/identity-connector-iota-stardust'
          - 'packages/identity-connector-universal'
          - 'packages/identity-service'
          - 'packages/identity-rest-client'
          - 'apps/identity-cli'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

    services:
      universal-resolver:
        image: iotaledger/uni-resolver-driver-iota:v0.2.0-alpha
        ports:
          - 8080:8080
        env:
          NETWORK: testnet

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Remove Mono-Repo Node Modules
        run: |
          rm package.json
          rm package-lock.json

      - name: Check package version does not contain -next
        run: |
          cd ${{ github.event.inputs.package }}
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo Package Version $PACKAGE_VERSION
          if [[ $PACKAGE_VERSION == *"-next"* ]]; then
            echo "Error: package version contains -next"
            exit 1
          fi

      - name: Run Dist
        run: |
          cd ${{ github.event.inputs.package }}
          npm install
          npm run dist

      - name: Cleanup package properties
        run: |
          cd ${{ github.event.inputs.package }}
          npm pkg delete scripts
          npm pkg delete devDependencies

      - name: Publish
        run: |
          cd ${{ github.event.inputs.package }}
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
